### ISSUE TITLE
Cordova plugin build not working for Android

### ISSUE THREAD

**Issue by GrahO23** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#140]
Hi

Are the following build instructions still supported?

cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android
cordova platform add ios
cordova prepare
..

I'm building with cordova v5.2.0 and Mobile SDK 4.0

cordova build android

Produces a valid APK (which I can install and run and other plugins work) however non of the salesforce plugin class files are in the app so cordova require fails

for example:

cordova.require("com.salesforce.plugin.oauth")
Produces:
cordova.js:59 Uncaught module com.salesforce.plugin.oauth not found

I've tried to build in Android studio by importing the platforms/android folder which can build the app without Salesforce Mobile SDK. 

Trying to import the two salesforce libraires I need ( SalesforceSDK & Smartstore ) produces a load of missing dependencies such as com.google.volley.

What's the correct way to import the Salesforce cordova plugin, I want to avoid forcedroid as I've got an existing project that is ionic based.

iOS works fine with the above build.

Thanks

**Comment by toddhalfpenny** [comment]
Hi,

I think there are some issues with doing this through `cordova build android` at the moment. I have got this working by importing into Android Studio following the cordova prepare and then building from within there.

I also am seeing issues with adding other plugins... I'm working on testing a theory as to what the issue can be. I think that if you want to use other plugins then at the moment you need to add them first, then the Android platform and lastly add the SF plugin. Like I said though this is a theory at the moment... but my testing seems to hold true so far.

**Comment by GrahO23** [comment]
Thanks Todd , still no luck.

Looking at forcedroid 

I updated to latest cordova
npm install -g cordova (5.2.0)

and install android platform 5.0.0
cordova platform add android@5.0.0

I still get no salesforce cordova plugins on launch (building with Android Studio ) and now get two activities with android.intent.category.LAUNCHER in the Manifest...

**Comment by GrahO23** [comment]
Ok So now 

cordova.require("com.salesforce.plugin.oauth") 

returns the javascript api so that's loading but 

when we go native in soupExists in com.salesforce.plugin.smartstore.js

I get the following exception 

W/System.err( 7329): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin" on path: DexPathList[[zip file "/data/app/com.salesforce.coba-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

So obviously still missing the classes.

Any help!

**Comment by toddhalfpenny** [comment]
Looks like you're hitting the same issues as me, though instead of adding support:multidex I swapped the line in build.gradle to be `compile "com.google.android.gms:play-services-gcm:7.5.0"` instead of `compile "com.google.android.gms:play-services:7.5.0"` as I'm not sure the project needs all the play services (should prob ask @bhariharan his views on this).

The 2 LAUNCHER (and 2 icons on apps screen) issue I think is to do with the order again. I have found if I add the SF plugin last then it comments out some of the section in the AndroidManifest.xml... and then it works. I'm still not 100% sure of why/how this is all happening, but it's good to hear I'm not the only one seeing this... and I'll be sure to push PRs/comments whenever I get a bit further.

**Comment by toddhalfpenny** [comment]
@GrahO23 I have also hit the `ClassNotFoundException` previously. Can you confirm that you have a _platforms/android/SmartStore_ directory and also that you're _platforms/android/settings.gradle_ looks like this?
```
// GENERATED FILE - DO NOT EDIT
include ":"
include ":CordovaLib"
include ":SalesforceSDK"
include ":SmartStore"
include ":SmartSync"
include ":SalesforceHybrid"
```
I could be that some post install work has not taken place?

**Comment by GrahO23** [comment]
Hi Todd

Yes settings.gradle looks the same

// GENERATED FILE - DO NOT EDIT
include ":"
include ":CordovaLib"
include ":SalesforceSDK"
include ":SmartStore"
include ":SmartSync"
include ":SalesforceHybrid"

Also platforms/android/SmartStore directory present

**Comment by toddhalfpenny** [comment]
OK. Erm... might be worth checking through this thread as I posted the same error there and the fix was to make sure shelljs is in place. It could be that the method to use to import the libs has caused this (apologies if you changed this).
https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/970

**Comment by GrahO23** [comment]
Hi Todd,

I've got shelljs installed locally ( and forcedroid for good measure) but still get 

W/System.err( 2080): java.lang.ClassNotFoundException: com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin
W/System.err( 2080): 	at java.lang.Class.classForName(Native Method)
W/System.err( 2080): 	at java.lang.Class.forName(Class.java:309)
W/System.err( 2080): 	at java.lang.Class.forName(Class.java:273)
W/System.err( 2080): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
W/System.err( 2080): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
W/System.err( 2080): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err( 2080): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
W/System.err( 2080): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err( 2080): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 2080): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err( 2080): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 2080): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 2080): 	at android.os.HandlerThread.run(HandlerThread.java:61)

The SDKUpdate script runs during platform add with no errors.

**Comment by GrahO23** [comment]
OK, without running cordova build ( only prepare) , I imported into Android Studio with the dex changes and 4g heap. 

Now I get

08 14:15:50.550 3762-3821/com.salesforce.coba W/SmartStorePlugin.execute: Applications need to call SalesforceSDKManagerWithSmartStore.init() first.
                                                                             java.lang.RuntimeException: Applications need to call SalesforceSDKManagerWithSmartStore.init() first.
                                                                                 at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getInstance(SmartStoreSDKManager.java:128)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.getSmartStore(SmartStorePlugin.java:577)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.soupExists(SmartStorePlugin.java:306)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$1400(SmartStorePlugin.java:58)
                                                                                 at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:160)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:818)

Which code calls the init, before 4.0 it has the com.salesforce.coba.SplashScreenActivity which was inject in by the post script.

In 4.0 SDK I now have com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity injected into the Manifest?

       <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/app_name" android:name="com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity" android:theme="@android:style/Theme.Black.NoTitleBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

But this doesn't seem to be executing the SalesforceSDKManagerWithSmartStore.init()??

@bhariharan

**Comment by toddhalfpenny** [comment]
Have you got any other plugins at all? I found that I saw this `init` error if I had other plugins.
If you have others too then you could try this;
* remove SF plugin
* remove and re-add platform
* re-add SF plugin.
* change the jnidir.src in the _platforms/android/SmartStore/build.gradle_
* import into AS and run from there

Following this process I can repeatedly get an APK installed that does allow me access to the SmartStore

**Comment by bhariharan** [comment]
Sorry I'm late to the party here. We just made a patch release - ```4.0.2```.

@GrahO23 Could you try the following steps and let me know if they work?
* Create a local directory.
* ```npm install forcedroid```
* ```npm install shelljs```
* Use ```node_modules/.bin/forcedroid``` to generate an app.
* Follow the output instructions at the end of the script to import the app into ```Android Studio```.
* Compile and launch the app.

**Comment by bhariharan** [comment]
I have verified the above steps work. Please reopen this issue if you are still seeing errors.

**Comment by AnchalBhardwaj** [comment]
I tried with the below mentioned steps, but still doesn't work: 

- Create a local directory.
- npm install forcedroid
- npm install shelljs
- Use node_modules/.bin/forcedroid to generate an app.
- Follow the output instructions at the end of the script to import the app into Android Studio.
- Compile and launch the app.

Below error is thrown and a popup- 'Unfortunately, app has stopped': 

- 5-02 15:30:31.534 2542-2542/com.test.testapp W/art: Attempt to remove non-JNI local reference, dumping thread
- 05-02 15:30:31.535 2542-2542/com.test.testapp E/SysUtils: ApplicationContext is null in ApplicationStatus
- 05-02 15:30:31.595 2542-2542/com.test.testapp W/chromium: [WARNING:resource_bundle.cc(285)] locale_file_path.empty()
- 05-02 15:30:31.597 2542-2542/com.test.testapp E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
- 05-02 15:30:31.597 2542-2542/com.test.testapp E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
- 05-02 15:30:31.597 2542-2542/com.test.testapp E/chromium: [ERROR:gl_surface_egl.cc(327)] No suitable EGL configs found.
- 05-02 15:30:31.597 2542-2542/com.test.testapp E/chromium: [ERROR:gl_surface_android.cc(23)] GLSurfaceEGL::InitializeOneOff failed.
- 05-02 15:30:31.597 2542-2542/com.test.testapp E/chromium: [ERROR:browser_main_loop.cc(698)] GLSurface::InitializeOneOff failed
- 05-02 15:30:31.748 2542-2542/com.test.testapp E/DataReductionProxySettingListener: No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
- 05-02 15:30:31.770 2542-2583/com.test.testapp W/AudioManagerAndroid: Requires BLUETOOTH permission
- 05-02 15:30:31.887 2542-2542/com.test.testapp W/art: Attempt to remove non-JNI local reference, dumping thread
- 05-02 15:30:31.918 2542-2542/com.test.testapp W/AwContents: onDetachedFromWindow called when already detached. Ignoring
- 05-02 15:30:31.934 2542-2542/com.test.testapp D/SystemWebViewEngine: CordovaWebView is running on device made by: unknown
- 05-02 15:30:32.035 2542-2542/com.test.testapp W/art: Attempt to remove non-JNI local reference, dumping thread
- 05-02 15:30:32.035 2542-2542/com.test.testapp W/art: Attempt to remove non-JNI local reference, dumping thread
- 05-02 15:30:32.751 2542-2581/com.test.testapp W/chromium: [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
- 05-02 15:30:32.771 2542-2607/com.test.testapp A/chromium: [FATAL:gl_surface_android.cc(58)] Check failed: kGLImplementationNone != GetGLImplementation() (0 vs. 0)
- 05-02 15:30:32.772 2542-2607/com.test.testapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 2607 (GpuThread)


Does the above steps still work for creating simple forcedroid hybrid app
