### ISSUE TITLE
Cordova build does not work for Android

### ISSUE THREAD

**Issue by coderReview** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#166]
Running ``cordova build android`` does not work.

**Comment by coderReview** [comment]
Investigating this I found the following
The issue is caused by the cordova build system which always overwrite the settings.gradle file (see cordova/lib/build.js file inside platforms/android folder)
Dependencies should be added to project.properties file and build information to build-extras.grade file.

**Comment by bhariharan** [comment]
Good to know. Right now, we only support building through ```Android Studio``` or using ```. gradlew assembleDebug``` directly from command line.

**Comment by bhariharan** [comment]
@coderReview I'll take a look at trying to make ```cordova build``` work. Thanks for your preliminary findings.

**Comment by elviejokike** [comment]
Hi, do you have already a fix for android build with cordova?

**Comment by toddhalfpenny** [comment]
Instead of using the cordova build you can call the gradlew commands instead, this way you can avoid having to open Android Studio.

**Comment by elviejokike** [comment]
Not an option.. we build the whole project in a continuos integration environment using Docker... salesforce is not the only plugin we use.  The project is always rebuild using cordova (that is the idea of this plugins). We reported this issue to also to one your colleagues from Salesforce who was around last days to Philips Research.

**Comment by BrettMN** [comment]
How long has `cordova build android` not been supported?  

According to [Mobile SDK Development Guide](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_run_android.htm) we should be using `cordova prepare android` and `cordova compile android` to build our apps.  Since `cordova build` is just short hand for
```
cordova prepare android
cordova compile android
```

according to the [Cordova docs](https://cordova.apache.org/docs/en/4.0.0/guide/cli/#build-the-app) shouldn't build also be supported?

Or is `cordova compile` not supported?

**Comment by sjaak-meulen** [comment]
I've been looking through the setup of the android plugin for cordova and found there's a lot of issues with the way it is setup, compared to how I would expect a cordova plugin to be setup. I would suggest a solution to this problem is to follow the standard process for cordova plugins. This would involve the following steps:

1) Isolate the SalesforceMobileSDK-Android dependencies and remove these from this repository (I would strongly suggest putting them in a maven repository, as it'd allow you to use gradle's 'compile' option to include the three dependencies)
2) Include these files through a build.gradle file located in the android project root
3) Modify the plugin.xml file and include the android source files that remain (e.g. cordova specific files) and include the build.gradle file as a framework reference

This would mean that the non-cordova files are pre-compiled and included in the project, and gradle would compile the resulting jar files into the project together with the cordova plugin files.

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.

**Comment by RayDeCampo** [comment]
@huminzhi is there a timetable for this to be released?  In the meantime what is the best way to use the fixed version of the plugin in our development work?

**Comment by bhariharan** [comment]
@RayDeCampo We don't support ```cordova build``` currently. We do, however, support importing the project into ```Android Studio``` and building, or using ```gradle``` directly from the command line. We have verified that both these paths work in the latest production version (```4.1.2```).
