### ISSUE TITLE
Query _soup property failed in left outer join smart query if the right side record is not existing

### ISSUE THREAD

**Issue by lingjunjiang** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#202]
Hi 

I'm not sure if this should be posted here, as it's related to SmartStore query in Salesforce Mobile SDK.

The issue is when using left outer join in smart query. It happens when querying _soup instead of inidividual properties on the right side soup and there is no corresponding record on the right side. It indeed works when right side has record. I wanted to query _soup is because I wanted to query all properties of the right side soup, so like * in normal sql, like below, the first one doesn't work as expected, but the second works fine.

1. Query with _soup
select a.{SoupA:Id}, b.{SoupB:_soup} from {SoupA} as a left outer join {SoupB} as b on a.{SoupA:BId} = b.{SoupB:Id} where a.{SoupA:Id} = '1';
1.1. When SoupB has corresponding record:
  Expect: return 1 record, with both SoupA.Id and the complete SoupB record.
  Actual: true
1.2. When SoupB has no corresponding record:
  Expect: return 1 record, with SoupA.Id and null for SoupB
  Actual: false, no record is returned at all

2. Query with inidividual property on right side soup
select a.{SoupA:Id}, b.{SoupB:Id} from {SoupA} as a left outer join {SoupB} as b on a.{SoupA:BId} = b.{SoupB:Id} where a.{SoupA:Id} = '1';
2.1. When SoupB has corresponding record:
  Expect: return 1 record, with both SoupA.Id and SoupB.Id
  Actual: true
2.2. When SoupB has no corresponding record:
  Expect: return 1 record, with SoupA.Id and null for SoupB.Id
  Actual: true

I know maybe we should not use _soup property because it is not created by us when inserting a record to a soup, because it's more like a native self-reference to the record itself. But is it possible to fix the problem described in 1.2 above? That would be really helpful as this is a shortcut for querying like b.* instead of iterating all fields.

Thanks.

**Comment by wmathurin** [comment]
SmartStore uses sqlcipher which itself is based on sqlite.

Each soup has a corresponding database table.
Indexed fields have a corresponding column in the database table for the soup.

The SmartStore code takes care of populating columns for indexed fields when you do creates or updates.

At query time, the SmartStore code takes care of replacing {soup} with the corresponding table name and {soup:path} with the corresponding column name. The resulting SQL queries are executed without further changes.

What you are describing is due to sqlite handling of joins and not something we can change.

**Comment by lingjunjiang** [comment]
Thanks.
