### ISSUE TITLE
Mobile SDK modules gradle build

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#227]
I added this plugin to my Cordova project and am running it on Android platform. Every time I run it, the four modules : SalesforceHybrid, SalesforceSDK, SmartStore, SmartSync, get compiled in each Gradle build. This Takes up a lot of compilation time generally. Is there any workaround to avoid this and make it a one time thing?

**Comment by bhariharan** [comment]
@harshalijain There's no way to avoid first time compilation cost, since we compile from sources. However, `Android Studio` is pretty good with recompilation time, especially if no native changes have been made. Also, this forum is reserved for known bugs/issues in the `Mobile SDK`. For everything else, please use our [Google+ Community](https://plus.google.com/u/1/communities/114225252149514546445).
