### ISSUE TITLE
Enhancement - Add the ability to specify default login host in the Hybrid app templates.

### ISSUE THREAD

**Issue by patnaikshekhar** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#235]
Users should have the ability to specify default login hosts, when they're using a custom login page. The native iOS/Android version of the SDK supports this by adding a key to the default plist file or servers.xml respectively. It would be nice to be able to specify this in the bootconfig.json file.

I hope I'm posting this enhancement to the correct repository.

**Comment by bhariharan** [comment]
@patnaikshekhar You can use the `Android/iOS` way in a hybrid app too. What's missing?

**Comment by patnaikshekhar** [comment]
It will be nice to be able to do this with configuring the Hybrid app bootstrap.json file instead of having to do this in xcode. That way it becomes more configuration than code for people who really don't know much about XCode or Android studio.

**Comment by patnaikshekhar** [comment]
In addition, it would also be nice to be able to specify whether a status bar is required and whether the settings option should be visible in the bootconfig.json file itself instead of editing the implementation files. [These are all nice to haves]

How does the bootstrap.json file provide the required inputs to the Objective C/Java Code? Does it override the bundle at runtime?

**Comment by BrettMN** [comment]
@bhariharan Since the `platforms` folder is generated code it would be nice to be able to not store it in version control.  As long as manual changes are required in the `platforms` folder it will have to be included.  Otherwise the error prone process of manually updating the contents of the `platforms` folder will be required for each new setup of the project. 

What is missing:  The ability to safely and repeatable clone the repository and restore the platforms with the `cordova prepare` command without making manual changes to the resulting generated code.

**Comment by bhariharan** [comment]
@patnaikshekhar I understand the desire to steer clear of `Android Studio` and `Xcode` for hybrid developers, but this is unavoidable while using our plugin, since our plugin is native library heavy. We seek to minimize the requirement to muck around with native code by providing an `xml` way to override in `Android` and a `plist` equivalent in `iOS`, which are configuration files.

@BrettMN Our plugins are native heavy and hence, we do have post install steps that run to move things in their correct locations. We do require `Android Studio` and `Xcode` to run.

That being said, thanks for your inputs. We will take your suggestions into consideration for a future release.
