### ISSUE TITLE
Index for boolean type is inconsistent in iOS and Android

### ISSUE THREAD

**Issue by lingjunjiang** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#238]
Dear Team,

We recently found an issue when inserting an Javascript with a boolean field which is as an index field. We tried to use string and integer as the index type for the boolean property. However, when using string as the index type, it stores "1" / "0" in iOS, while in Android it is "true" / "false". When using integer as index type, it stores 1 / 0 in iOS, while in Android it is null no matter the Javascript property is true or false. This inconsistent behaviour makes it impossible to implement platform independent apps, for example, when later querying this soup based on the boolean property's index.

Code Example:
Registered Soup User:
{
    'path': 'name',
    'type': 'string'
}, {
    'path': 'active',
    'type': 'string'
}
Test Records:
[
    {name: 'record 1', active: true}, 
    {name: 'record 2', active: false}
]
It only returns correct result when using the following In iOS:
'select * from User where {User:active} = 1'
'select * from User where {User:active} = 0'
It only returns correct result when using the following in Android:
'select * from User where {User:active} = \'true\''
'select * from User where {User:active} = \'false\''

If the active property is indexed as an integer, then it still only works in iOS when using the following:
'select * from User where {User:active} = 1'
'select * from User where {User:active} = 0'
However, it NEVER works in Android because the indexed value is null.

Currently, we have to check and write specific code for iOS and Android separately, there would be tons of places of these hack code as long as there are many places need to query based on boolean property. I was wondering if this is a known issue and if it could be solved from Mobile SDK framework level?

Thanks.

**Comment by wmathurin** [comment]
As a workaround could you do the following:
```sql
select * from User where {User:active} = 1 or {User:active} = 'true'
select * from User where {User:active} = 0 or {User:active} = 'false'
```
It's not very elegant but should work.

**Comment by lingjunjiang** [comment]
@wmathurin Thanks for the suggestion, we are currently using similar workaround. It's not urgent, but for long term, it'd be great if this could be fixed at low level so client developers could work without knowing this. :-)

**Comment by sevem** [comment]
@wmathurin @lingjunjiang not for a long term, I would say a short middle term. My problem is quite simple. This workaround must be known, accepted and done by each single developer. And for sure this will be forgotten in some implementations.

**Comment by wmathurin** [comment]
@lingjunjiang @sevem To make it really work, we probably need to introduce a new index spec type for boolean (otherwise, on iOS, once Cordova hands over the NSDictionary to us, there is no way to know if you had the integer value 0 or 1 or if you had a boolean). So I'll change the label to enhancement. And we will look at adding that index spec type in a future release.

**Comment by wmathurin** [comment]
Actually there is a simple solution:
* index the field as a JSON1 field
* in SmartSql look for 0 (false) or 1 (true) because SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).

For tests demonstrating queries against boolean fields, please see:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2553
https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1719
