### ISSUE TITLE
Unstable branch has wrong compiled libs for iOS?

### ISSUE THREAD

**Issue by GrahO23** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#248]
@bhariharan 

Hi Trying to use the WKWebview unstable @bb7f3de and getting UIWebview instantiated by default.

To see what's going on added a call to setupRootViewController in AppDel+Hybrid

    SFHybridViewController* hb = (SFHybridViewController*)self.viewController;
    BOOL useUIWebView = [hb useUIWebView];

Getting an exception :

[SFHybridViewController useUIWebView]: unrecognized selector sent to instance 0x7f7f5ba04eb0'
*** First throw call stack:

Wrong compiled libSalesforceHybridSDK.a for header?

Thanks!

Graham

**Comment by bhariharan** [comment]
@GrahO23 Yes - the `.a` files on `unstable` have not been updated yet, and that's intentional since we don't want the repository size to grow too large by versioning binaries. Typically, we only check in updated binaries when we release. If you want to try our plugin locally, you can run `. tools/update.sh -b unstable` locally from the root of this repo. This will pull the latest from the source repositories and allow you to use `WKWebView` with the plugin before our upcoming release.

**Comment by GrahO23** [comment]
@bhariharan Thanks for the tip
