### ISSUE TITLE
Will Mobile SDK support Community Guest User?

### ISSUE THREAD

**Issue by lingjunjiang** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#270]
Dear friends,

Currently, app user has to login to Salesforce to get proper access token and create local smartstore. As lightning community pages can be public and lightning components might also work via lightning out for guest users (already on the road map), is there a plan to support Guest User in Mobile SDK apps?

For example, is it possible to get a Guest User's access token, or use Mobile SDK apps without login for guest users?

Thanks for any feedback.

**Comment by bhariharan** [comment]
@lingjunjiang When you say `Guest User`, are you referring to an unauthenticated user? Most of the core functionality in `Salesforce` requires an authenticated user. For example, any REST API call that's made requires an access token, which requires the user to be authenticated. However, we do support `SmartStore` in the unauthenticated use case (global `SmartStore`). We do caution that this should NOT be used to store sensitive user-specfic or org-specific data, since it won't be wiped and will be accessible to all users within your app.

**Comment by lingjunjiang** [comment]
@bhariharan Thanks for replying the question. Yes, I mean the unauthenticated Guest User who can view public sites and public lightning pages of a lightning community (created via Customer Service (Napili) Template). And what I got from Lightning Trailblazers Group is the lightning components would support guest user, for example, it will be allowed to execute lightning.use() without passing access token when using lightning out for guest user (still on the roadmap).

My use case is we have a lightning community, and there are some public pages where guest user can visit, and if user needs to get further info, then he/she needs to login to the community. In the meantime, we would like to have a hybrid mobile app behaving the same, means the app would use lightning components to display some public info via lightning out before login. And if they need further actions, then they need to login to the app (via the standard login page as it is now in the mobile sdk)

After a second thinking, I think this is possible because the standard login page is opened only when the app explicitly calls cordova.require('com.salesforce.plugin.oauth').getAuthCredentials() method. As long as the lightning.use() method supports guest user (in this case, we don't need to get access token of the guest user, this is the main problem using lightning out), we can use lightning components without login. If user needs further actions, for example, via REST to get more data, then call getAuthCredentials() to login and get a proper access token as an authenticated user. Am I right?

**Comment by bhariharan** [comment]
@lingjunjiang I can't speak to the specifics of how `Lightning` works since we don't deal with that specifically. However, it sounds like you could make this work with deferred authentication, which `Mobile SDK` supports. Basically, you would start with a hybrid app unauthenticated and call `authenticate` on our `OAuth` plugin when you want to authenticate. Feel free to post on our community [here](https://plus.google.com/u/1/communities/114225252149514546445) too, to discuss with other `Salesforce` users.

**Comment by lingjunjiang** [comment]
Thanks @bhariharan, this is already enough information.
