### ISSUE TITLE
Auto logout issue for iOS

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#329]
Hi,
From Mobile SDK v5.0 onwards,in Android, the ClientManager.java class constructor added a new Boolean variable _revokedTokenShouldLogout_ , this variable was true by default and hence sometimes the user is logout automatically before going inside the application, but our application has the functionality to prompt the user when token is revoked.
I have modified the above class to default this variable to false as per our requirements, but can you provide assistance on how to modify the similar functionality on iOS.

Thanks.

**Comment by bhariharan** [comment]
@harshalijain There is no similar mechanism on `iOS` and this is intentional. We will probably take away `revokedTokenShouldLogout` from `Android` as well in the future. The reason is that when the refresh token is revoked remotely by an admin, the user should not have the option to avoid logging out, the app should be logged out per security requirements. This is by design.
