### ISSUE TITLE
Account Manager issue for supporting Android for Work environment

### ISSUE THREAD

**Issue by harshalijain** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#332]
Hi,

We are running our Salesforce based application on _Android for Work_ environment which has a configuration that does not allow adding device accounts. Previously, we had raised the issue [https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1469](url) regarding the same. After further investigation, it was found that the method _addAccount_ was causing the issue. What are the implications of using _addAccountExplicitly_ instead to perform same functionality as it directly adds account to device and is not restricted in Android for Work environment?
Is it possible to make this particular change as it would solve blank screen issue on application startup.

Thanks.

**Comment by bhariharan** [comment]
@harshalijain The short answer is that we can't switch from `addAccount()` to `addAccountExplicitly()` because there are gaps between those 2 APIs. For example, there is no way to use `AbstractAccountAuthenticator` or a callback mechanism with `addAccountExplicitly()`. These gaps prevent us from switching to that API since we need to have a custom `Authenticator` for token management.
