### ISSUE TITLE
7.0.0 release does not work with common cordova plugins

### ISSUE THREAD

**Issue by dfattlar** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#435]
forcehybrid version:  7.0.0
cordova version: 8.1.2
platform: Android

Issue: When following the upgrade path in the SDK documentation, the app breaks when building to Android device if you use the cordova-plugin-camera or cordova-plugin-email-composer. The error reported in the build process is "error: package android.support.v4.content does not exist"

To recreate:
- run forcehybrid create
- add cordova-plugin-camera plugin
- remove salesforce plugin and re-add as described in SDK docs (pg. 30)
- run cordova prepare
- Observe that android app will no longer build to device as the Run tasks fails with error "error: package android.support.v4.content does not exist"
...
(This can also be recreated when creating the app through cordova command line)
- Create cordova app
- add cordova-plugin-camera plugin
- run app, observe it builds to device correctly
- add salesforce plugin
- run cordova prepare
- Observe that android app will no longer build to device as the Run tasks fails with error "error: package android.support.v4.content does not exist"

I tried making updates to the manifest and gradle, but without being an Android expert I'm not sure the best way to work around this issue. Since these are common cordova plugins, my hope is that a solution can be identified where adding such plugins works out of the box with forcehybrid.

**Comment by bhariharan** [comment]
@dfattlar This is not an issue with our plugin, it's an issue with those plugins - they don't support `AndroidX` or `Android Jetpack` yet. Please file issues with those plugins (see details [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1834)).

**Comment by jaygauten** [comment]
Just to share my solution for plugins that are not maintained by the author anymore:

- one way is to fork the plugin and refactor it to support androidx, check this guide: [AndroidX Migrate](https://developer.android.com/jetpack/androidx/migrate#migrate). there are two way to do this:
1. use android studio to automatically migrate it to androidx, or 
2. manually modify the java source to use androidx namespace instead of the legacy support namespace. check the artifact mappings.

- another one is to downgrade gradle version from `3.2.1` to `3.1.`* in your `platforms/android/build.gradle file`
