### ISSUE TITLE
App is going to background after Login successful

### ISSUE THREAD

**Issue by jaygauten** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#444]
Andoid Version: 8.0
Salesforce SDK Cordova Plugin Version: 6.2
Cordova Version: 8.0.0

Issue: When LoginActivity was loaded and place the app in a background state (even just tapping the task manager)  then go back to the app and try to log in, on successful login flow the LoginActivity was destroyed but the onResume on SalesforceDroidGAPActivity was not executed causing the app failed to load after login

other observation:
- the issue found in the finish() part after log in
- on happy path the SalesforceDroidGAPActivity is running onresume right after the finish() call in LoginActivity()
- when the issue occured the app is being killed without any crash info from the logcat

**Comment by wmathurin** [comment]
Did you mean SalesforceDroidGapActivity rather than GAPActivity?
When you install the Mobile SDK plugin, your application should use the SalesforceDroidGapActivity instead of GAPActivity.

**Comment by jaygauten** [comment]
@wmathurin yes it is SalesforceDroidGAPActivity, updated the issue detail

**Comment by jaygauten** [comment]
Also tried in with the configuration below:

Android Version: 8.0
Salesforce SDK Cordova Plugin Version: 7.0
Cordova Version: 8.1.2
Cordova Android: 7.1.2

i tried creating a new project (using any of the sample apps available and without any other plugins installed but the) and reproduced the issue

**Comment by wmathurin** [comment]
Are you creating your application with [forcehybrid](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_new_forcehybrid_project.htm) or are you using the cordova CLI directly?

**Comment by frankvlocity** [comment]
Hi @wmathurin, Joerian created with the forcehybrid tool you provided.

**Comment by wmathurin** [comment]
What do you have in your bootconfig.json?

**Comment by frankvlocity** [comment]
This is our app bootconfig which also has this app go to background issue since last Oct.  Jay will post his bootconfig.json from generated app.
{
    "remoteAccessConsumerKey":"xxxx",
    "oauthRedirectURI": "vlocity://login.salesforce.com/services/oauth2/success",
    "oauthScopes": [
        "web",
        "api"
    ],
    "androidPushNotificationClientId":"4158XXXX",
    "isLocal": true,
    "startPage": "index.html",
    "errorPage": "error.html",
    "shouldAuthenticate": true,
    "attemptOfflineLoad": false
}

**Comment by jaygauten** [comment]
Hi @wmathurin here's the bootconfig of the newly generated sample app

`{
    "remoteAccessConsumerKey": "<removed>",
    "oauthRedirectURI": "testsfdc:///mobilesdk/detect/oauth/done",
    "oauthScopes": ["api","web"],
    "isLocal": true,
    "startPage": "AccountEditor.html",
    "errorPage": "error.html",
    "shouldAuthenticate": true,
    "attemptOfflineLoad": true,
    "androidPushNotificationClientId": ""
}`

**Comment by wmathurin** [comment]
I can reproduce the issue. Thanks for reporting this bug.

**Comment by frankvlocity** [comment]
Thank you very much for taking time verify @wmathurin. Do you have an estimate when will you have fix in so we can set expectation for customers. Appreciated!

**Comment by frankvlocity** [comment]
hi @wmathurin, Jay tried this fix, it seems working for us. Please verify and let us know. Thank you!

**Comment by wmathurin** [comment]
This is unfortunately by design because of a few reasons:
LoginActivity is on its own single task (this means there are no other activities on that task back stack). This can not be changed - it is required for the IDP and browser flow to work correctly.
Given the above point, back button behavior relies on where the call came from to go back to. If the app is backgrounded and then foregrounded, then the context becomes SalesforceSDKManager.getInstance().getApplicationContext().

Also, there are other reasons why we have special back button behavior.
See the current implementation:
```java
/**
 * A fix for back button behavior
 *
 * @return true if the fix was applied
 *         false if the key code was not handled
 */
protected boolean fixBackButtonBehavior(int keyCode) {
   if (keyCode == KeyEvent.KEYCODE_BACK) {

       /*
        * If there are no accounts signed in, we need the login screen
        * to go away, and go back to the home screen. However, if the
        * login screen has been brought up from the switcher screen,
        * the back button should take the user back to the previous screen.
        */
      final UserAccountManager accMgr = SalesforceSDKManager.getInstance().getUserAccountManager();
      if (accMgr.getAuthenticatedUsers() == null) {
         wasBackgrounded = true;
         moveTaskToBack(true);
         return true;
      } else {
         wasBackgrounded = true;
         finish();
         return true;
      }
   }
   return false;
}
```
One approach is to subclass LoginActivity and override fixBackButtonBehavior(int keyCode). We would recommend leaving the SDK implementation alone because fixing this will introduce other issues that are higher priority.

**Comment by jaygauten** [comment]
@wmathurin im not sure i understand your comment on the fixBackButtonBehavior, are you saying that from app background to foreground it should use the same logic?

given this PR - https://github.com/jaygauten/SalesforceMobileSDK-CordovaPlugin/commit/cbfe9e08bb2a90b1e7141e3ecdc6687b178c2367 - we got the idea from the logout process

also id like to ask that to subclass your implementation of LoginActivity we have to fork your repository and used the forked repo of the plugin in our HybridApp right? because we are using a continuous delivery for our app and manually adding a java code to the plugin is not a good idea

**Comment by frankvlocity** [comment]
@wmathurin will you or your team have a fix in soon?

**Comment by bhariharan** [comment]
@frankvlocity As I have mentioned in the past over email, there are a few reasons why we don't want to change this behavior - it breaks a few other more important login flows. As a workaround, we have provided a few methods in `LoginActivity` for apps to override to tweak the flows that occur during key flows in `LoginActivity`. My recommendation is to create a subclass of `LoginActivity` and override the behavior of `finish()` for instance to launch a certain way. This does not require forking the plugin - it only involves adding a subclass implementation within your app.

**Comment by frankvlocity** [comment]
@bhariharan @wmathurin thanks for reply. Just came back from vacation. I am a bit confused. The android app is going to background as an out of box behavior. So are you saying it will not be fixed or you are just saying @jaygauten's fix is not ideal because changed your intended behavior. 

We will look into your suggest on how to subclass it our own. Will you provide a fix in your next release too? 

Many thanks!

**Comment by bhariharan** [comment]
@frankvlocity It probably won't be fixed in the next release either for the following reasons:
- Fixing this is likely to introduce issues with a few other login flows that are more down-the-middle use cases than this flow.
- The probability of users backgrounding the app on the login screen and bringing it back up to login multiple times is sufficiently low to not risk breaking other flows.
- There are workarounds available to apps that want to plug this by overriding `LoginActivity` and tweaking the behavior in the sub-class.

**Comment by frankvlocity** [comment]
@bhariharan  We are trying the workaround you suggested . But the probability app go to background is very often. almost every time. Also they cannot launch it from the active apps in the background, which will bring back the login screen again. The trick is to launch the app from home app screen. Customer is really not happy for this behavior.

**Comment by bhariharan** [comment]
@frankvlocity I understand. I can take another stab at attempting a fix without affecting the other flows, but it's probably going to be in the longer term.

**Comment by murilodag** [comment]
Hello all,

Is there any update in this ticket? This is also reproducible with the native salesforce sdk.
