### ISSUE TITLE
High Priority: Unable to proceed from passcode screen on android app

### ISSUE THREAD

**Issue by va1bhav** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#498]
*** We have a go live this week ***
I have a hybrid mobile app built using Salesforce Mobile SDK version  5.0.0, now we have updated all to SDK 7.3.0 .

In android device, when I install new version of the app on top of old version, that is update the application. I am unable to proceed past the passcode screen. 
Also, we allow only 4 digit passcode but after updating the application, the 4 digit passcode restriction is also not working.

PFA screenshot.
![IMG_1429](https://user-images.githubusercontent.com/33320222/73658574-92dc6480-46ba-11ea-9965-874f1eb47f69.jpg)

This is working fine in iOS where we are updating from v6.2.0 to v7.3.0.

@wmathurin @bhariharan

**Comment by brandonpage** [comment]
Hi @va1bhav, I believe there is a simple solution to this.   

Background: Due to UX changes we needed to switch to a model where we know the passcode length.  If we do not know the length you will see a one time upgrade screen (that you are seeing in the above screenshot).   The first time after you correctly enter your passcode the length will be stored and better UX will be shown in the future.  This is necessary because we have always treated the connected app length as a minimum instead of exact length like we do now.  However, there is an API that will allow you to skip the upgrade step seen above if you can guarantee the passcode length.

If you enter the correct 4 digit passcode and the enter (check mark) button on the keyboard do subsequent runs show a consistent result?  

API Solution:   If you can guarantee the passcode length is the minimum required by the connected app  (use caution here as the SDK has never enforced this until 7.0) then you can call PasscodeManager's `setPasscodeLengthKnown`.    

How did you not hit the exact same issue on iOS?  The only way you would not see this one time upgrade screen there is if you did the equivalent, which would be to set `forcePasscodeLength` to YES in the AppLockViewConfig.

**Comment by va1bhav** [comment]
Hi @brandonpage ,

Thank you for quick response.
Apologies if i was not clear earlier. My concern is not that I am getting passcode screen.
Concern here is that in Android, after entering the correct 4 digit passcode and the enter (check mark) button on the keyboard I am not redirected to next screen. Instead of redirection, the 4 digit passcode restriction is removed.

When I again re-enter passcode and click on (check mark) button on the keyboard, nothing happens.

Regarding iOS, I do get the passcode screen after app update but after entering correct passcode, app works as expected.

**Comment by brandonpage** [comment]
Okay, I understand the issue now.  Without digging through the code history I think it is very likely this issue is caused by an Android keystore migration.  If we did one in 6.0 (which I believe we did) there would have been an upgrade step; however that upgrade step would have been removed in 7.0.  So going from 5.0 to 7.3 you missed some upgrade steps, which is why we do no recommend skipping an entire major version.

**Comment by va1bhav** [comment]
Thanks for the input here, I understand the recommendation point to go from 5.0 to 6.2 being the traditional approach. But is there a way we can jump to 7.3 by making any code/API changes?

As we have a major release and complete development and testing is done on 7.3, it would be difficult to change SDK now. Hope you understand the gravity of situation here.

**Comment by brandonpage** [comment]
@va1bhav  I believe I have found the missing upgrade step:  https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/58b3633bf20fd4fd7c37154ba245bffa7bca7416#diff-828b5694fc65de0bfb8dd2593f1eab73L305

I believe it would require temporarily forking/modifying the SDK (until all of your user are upgraded) but you can try replicating that `legacyHashForVerification` step as seen above.

**Comment by va1bhav** [comment]
@brandonpage I am unable to use below import statement, it seems UUIDManager class is not there now. legacyHashForVerification function works with this class only.

import com.salesforce.androidsdk.app.UUIDManager;

Is there anything different I can do here?

**Comment by va1bhav** [comment]
@brandonpage  Also I tried building android app with SDK v6.2, facing same issue with passcode screen as with SDK v7.3.

**Comment by brandonpage** [comment]
Passcode works on the Mobile SDK 5.0 but not after upgrading to 6.2?  If that was the case without modifications a lot of customers would have noticed around the time of its release.  I need more info in order to help you.  Did you override or modify anything?  Any logs? Can you debug and give me an idea of what's going wrong?

**Comment by va1bhav** [comment]
@brandonpage  I will try to generate debug logs for you. But there is nothing modified in SDK. If I do not update my SDK 6.2/7.3 on top of old version and rather delete the old app first then install the latest one, everything works as expected.

Issue is only when passcode is setup and we update the app using SDK v5.0 to v6.3 or v7.3.

**Comment by bhariharan** [comment]
@va1bhav You're upgrading from a version of Mobile SDK that's 3 years old to a new version. A lot has changed within the SDK across the multiple major versions fo the SDK. These upgrade steps have been added and removed in subsequent versions. Most of these changes are security improvements around encryption and key storage. With passcode specifically, there was a change made within `Android` that switched the underlying algorithm from `BouncyCastle` to `Conscrypt`. This requires users upgrading from older versions with passcode enabled to log out and log back in. Here's what I recommend:
- When the new app starts up, log the user out and wipe all data. When the user logs back in, everything should work fine.

There aren't too many other options at this point.

**Comment by Manjeetmetacube** [comment]
We got the same issue and its basically difference between two version of SDK and the way they are handling the passcode. In earlier SDK version if your connected app allows pin length say 4 then you can put the pin of either 4 or greater than that. 

But after update to newer SDK version you can put the pin of same length as of configured pin length in connected app settings.

This makes the validation failing while you update app from SDK 5 to 7 or 8.

We did a work around for this.
